Add 'showcsr' option

diff --git a/ssl/helper b/ssl/helper
--- a/ssl/helper
+++ b/ssl/helper
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Usage: ./helper newconfig|newkey|createcsr|signcsr|update|show|expiry|help client-name
+# Usage: ./helper newconfig|newkey|createcsr|showcsr|signcsr|update|show|expiry|help client-name
 
 # These lines taken from https://stackoverflow.com/a/1638397
 # Absolute path to this script, e.g. /home/user/pi/EosRemote/ssl/helper
@@ -43,6 +43,7 @@ help() {
   echo "newkey client-name     Creates a new RSA key for the client"
   echo "newconfig client-name  Creates an openssl configuration file for the client"
   echo "createcsr client-name  Creates a CSR for the client, from the config and key"
+  echo "showcsr client-name    Show the details of the CSR for the client"
   echo "signcsr client-name    Use the local CA to sign the CSR for the client,"
   echo "                       creating a new certificate"
   echo "update client-name     Creates a new certificate for the client, from the key"
@@ -295,6 +296,35 @@ createcsr() {
 
 
 
+showcsr_usage() {
+  usage showcsr
+}
+
+showcsr_help() {
+  help
+}
+
+showcsr_client() {
+  showcsr "$SSL_DIR/$1$CSR_FILE"
+}
+
+showcsr_ca() {
+  echo "showcsr CA - not applicable..."
+}
+
+showcsr() {
+  echo "CSR file: $1"
+  if file_exists "$1"; then
+    # CSR file exists, and is not empty
+    openssl req -in "$1" -noout -text
+  else
+    echo "Error: CSR file not found!"
+    exit 1
+  fi
+}
+
+
+
 signcsr_usage() {
   usage signcsr
 }
@@ -497,6 +527,23 @@ case $1 in
         ;;
       *)
         createcsr_client "$2"
+        ;;
+    esac
+    ;;
+  showcsr|showCSR|show_csr|show_CSR)
+    case $2 in
+      CA|ca|Ca|cA)
+        showcsr_ca
+        ;;
+      help)
+        showcsr_help
+        ;;
+      "")
+        showcsr_usage
+        exit 1
+        ;;
+      *)
+        showcsr_client "$2"
         ;;
     esac
     ;;
